# Generated by Django 3.0.8 on 2020-08-09 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import question.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Опрос')),
                ('data_publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('is_active', models.BooleanField(verbose_name='опубликован')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опрос',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=50)),
                ('id_user', models.IntegerField()),
                ('question_total', models.CharField(max_length=200)),
                ('poll_total', models.CharField(max_length=200)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResultsAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_user', models.IntegerField()),
                ('poll_total', models.CharField(max_length=200)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('question_type', models.CharField(choices=[('checkbox', 'checkbox'), ('radio', 'radio')], max_length=8, verbose_name='тип ответа')),
                ('images', models.ImageField(blank=True, default=None, upload_to='media/%Y/%m/%d')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Poll')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='Ответ')),
                ('point', models.IntegerField(default=0, verbose_name='балл')),
                ('question', models.ForeignKey(default=question.models.question_last, on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
